train_len: 4000000
val_len: null
Tx: 30
Ty: 30
hidden_size: 1000
embedding_size: 620
max_out_units: 500
vocab_size_en: 30000
vocab_size_fr: 30000
batch_size: 80
epochs: 6.4
vocab_source: "train"
load_last_model: false  
encoder_decoder: false
multiprocessing: true
test: false
