train_len: 30000
val_len: null
Tx: 30
Ty: 30
hidden_size: 256
embedding_size: 256
max_out_units: 64
vocab_size_en: 10000
vocab_size_fr: 10000
batch_size: 64
epochs: 1000
vocab_source: "train"
load_last_model: true
encoder_decoder: false