train_len: 100000
val_len: null
Tx: 10
Ty: 10
hidden_size: 100
embedding_size: 64
max_out_units: 50
vocab_size_en: 3500
vocab_size_fr: 5000
batch_size: 80
epochs: 1000
vocab_source: "train"
load_last_model: true
encoder_decoder: false
multiprocessing: true
